# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  simple-retrier
  
  A workflow that uses a jittery function to demonstrate a simple retrier.

Resources:
  JitteryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/jittery-function/
      Handler: jittery-function
      Runtime: go1.x

  SimpleRetrierStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: Simple-Retrier
      Policies:
        - LambdaInvokePolicy: 
            FunctionName: !Ref JitteryFunction
      DefinitionUri: statemachine/simple-retrier.asl.json
      DefinitionSubstitutions: 
        JitteryFunctionArn: !GetAtt JitteryFunction.Arn
